M48
; DRILL file {KiCad 8.0.8-8.0.8-0~ubuntu24.04.1} date 2025-05-06T14:10:31+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-06T14:10:31+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8-8.0.8-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
%
G90
G05
T1
X144.64Y-65.61
X144.64Y-71.39
T2
X150.65Y-86.0
X150.7Y-104.05
T3
X223.1Y-69.3
M30
