; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c6-devkitm-1]
; PLATFORM - TAG 55.03.31 - https://github.com/pioarduino/platform-espressif32/releases/tag/55.03.31
; ARDUNIO v3.3.1 based on ESP-IDF v5.5.1
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.31/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps = 
    adafruit/Adafruit NeoPixel
    SD
lib_extra_dirs = lib
build_flags =
    -Ilib/pressure.arduino.ICP201XX/src/ICP201xx
    -Ilib/pressure.arduino.ICP201XX/src
    -Ilib/LSM6DSL/src
    -Ilib/SparkFun_Toolkit/src
    -Ilib/SparkFun_AS7343_Arduino_Library/src
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D__U32_T_DEFINED

